# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
